2019-12-16 21:58:37 | Error | AuroraConstruktor | Exception: Diese Instanz hat bereits mindestens eine Anforderung gestartet. Eigenschaften können nur vor dem Senden der ersten Anforderung geändert werden. | InnerException: System.InvalidOperationException Diese Instanz hat bereits mindestens eine Anforderung gestartet. Eigenschaften können nur vor dem Senden der ersten Anforderung geändert werden. Void CheckDisposedOrStarted()
2019-12-16 21:58:37 | Error | AuroraConstruktor | Exception: Diese Instanz hat bereits mindestens eine Anforderung gestartet. Eigenschaften können nur vor dem Senden der ersten Anforderung geändert werden. | InnerException: System.InvalidOperationException Diese Instanz hat bereits mindestens eine Anforderung gestartet. Eigenschaften können nur vor dem Senden der ersten Anforderung geändert werden. Void CheckDisposedOrStarted()
2019-12-16 21:58:37 | Error | AuroraConstruktor | Exception: Diese Instanz hat bereits mindestens eine Anforderung gestartet. Eigenschaften können nur vor dem Senden der ersten Anforderung geändert werden. | InnerException: System.InvalidOperationException Diese Instanz hat bereits mindestens eine Anforderung gestartet. Eigenschaften können nur vor dem Senden der ersten Anforderung geändert werden. Void CheckDisposedOrStarted()
2019-12-17 10:07:52 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-17 10:07:52 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-17 19:17:08 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-17 19:17:08 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-17 19:57:20 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-17 19:57:20 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-17 20:09:56 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3/state Value:{"on":{"value":true}}:ConnectToNanoleaf | Exception: Fehler beim Senden der Anforderung. | InnerException: System.Net.Http.HttpRequestException Fehler beim Senden der Anforderung. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
WebException Die zugrunde liegende Verbindung wurde geschlossen: Unbekannter Fehler beim Empfangen.. System.Net.WebResponse EndGetResponse(System.IAsyncResult)
IOException Von der Übertragungsverbindung können keine Daten gelesen werden: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat. Int32 EndRead(System.IAsyncResult)
SocketException Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat Int32 EndReceive(System.IAsyncResult)
2019-12-17 20:09:56 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3/state Value:{"on":{"value":true}}:ConnectToNanoleaf | Exception: Fehler beim Senden der Anforderung. | InnerException: System.Net.Http.HttpRequestException Fehler beim Senden der Anforderung. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
WebException Die zugrunde liegende Verbindung wurde geschlossen: Unbekannter Fehler beim Empfangen.. System.Net.WebResponse EndGetResponse(System.IAsyncResult)
IOException Von der Übertragungsverbindung können keine Daten gelesen werden: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat. Int32 EndRead(System.IAsyncResult)
SocketException Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat Int32 EndReceive(System.IAsyncResult)
2019-12-17 20:09:56 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3/state Value:{"on":{"value":true}}:ConnectToNanoleaf | Exception: Fehler beim Senden der Anforderung. | InnerException: System.Net.Http.HttpRequestException Fehler beim Senden der Anforderung. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
WebException Die zugrunde liegende Verbindung wurde geschlossen: Unbekannter Fehler beim Empfangen.. System.Net.WebResponse EndGetResponse(System.IAsyncResult)
IOException Von der Übertragungsverbindung können keine Daten gelesen werden: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat. Int32 EndRead(System.IAsyncResult)
SocketException Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat Int32 EndReceive(System.IAsyncResult)
2019-12-17 20:14:49 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-17 20:14:49 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-17 20:17:14 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3/state Value:{"on":{"value":false}}:ConnectToNanoleaf | Exception: Fehler beim Senden der Anforderung. | InnerException: System.Net.Http.HttpRequestException Fehler beim Senden der Anforderung. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
WebException Die zugrunde liegende Verbindung wurde geschlossen: Unbekannter Fehler beim Empfangen.. System.Net.WebResponse EndGetResponse(System.IAsyncResult)
IOException Von der Übertragungsverbindung können keine Daten gelesen werden: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat. Int32 EndRead(System.IAsyncResult)
SocketException Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat Int32 EndReceive(System.IAsyncResult)
2019-12-17 20:17:14 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3/state Value:{"on":{"value":false}}:ConnectToNanoleaf | Exception: Fehler beim Senden der Anforderung. | InnerException: System.Net.Http.HttpRequestException Fehler beim Senden der Anforderung. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
WebException Die zugrunde liegende Verbindung wurde geschlossen: Unbekannter Fehler beim Empfangen.. System.Net.WebResponse EndGetResponse(System.IAsyncResult)
IOException Von der Übertragungsverbindung können keine Daten gelesen werden: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat. Int32 EndRead(System.IAsyncResult)
SocketException Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat Int32 EndReceive(System.IAsyncResult)
2019-12-17 20:17:14 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3/state Value:{"on":{"value":false}}:ConnectToNanoleaf | Exception: Fehler beim Senden der Anforderung. | InnerException: System.Net.Http.HttpRequestException Fehler beim Senden der Anforderung. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
WebException Die zugrunde liegende Verbindung wurde geschlossen: Unbekannter Fehler beim Empfangen.. System.Net.WebResponse EndGetResponse(System.IAsyncResult)
IOException Von der Übertragungsverbindung können keine Daten gelesen werden: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat. Int32 EndRead(System.IAsyncResult)
SocketException Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat Int32 EndReceive(System.IAsyncResult)
2019-12-17 20:29:28 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-17 20:29:28 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-17 20:31:18 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3/state Value:{"on":{"value":false}}:ConnectToNanoleaf | Exception: Fehler beim Senden der Anforderung. | InnerException: System.Net.Http.HttpRequestException Fehler beim Senden der Anforderung. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
WebException Die zugrunde liegende Verbindung wurde geschlossen: Unbekannter Fehler beim Empfangen.. System.Net.WebResponse EndGetResponse(System.IAsyncResult)
IOException Von der Übertragungsverbindung können keine Daten gelesen werden: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat. Int32 EndRead(System.IAsyncResult)
SocketException Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat Int32 EndReceive(System.IAsyncResult)
2019-12-17 20:31:18 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3/state Value:{"on":{"value":false}}:ConnectToNanoleaf | Exception: Fehler beim Senden der Anforderung. | InnerException: System.Net.Http.HttpRequestException Fehler beim Senden der Anforderung. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
WebException Die zugrunde liegende Verbindung wurde geschlossen: Unbekannter Fehler beim Empfangen.. System.Net.WebResponse EndGetResponse(System.IAsyncResult)
IOException Von der Übertragungsverbindung können keine Daten gelesen werden: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat. Int32 EndRead(System.IAsyncResult)
SocketException Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat Int32 EndReceive(System.IAsyncResult)
2019-12-17 20:31:18 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3/state Value:{"on":{"value":false}}:ConnectToNanoleaf | Exception: Fehler beim Senden der Anforderung. | InnerException: System.Net.Http.HttpRequestException Fehler beim Senden der Anforderung. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
WebException Die zugrunde liegende Verbindung wurde geschlossen: Unbekannter Fehler beim Empfangen.. System.Net.WebResponse EndGetResponse(System.IAsyncResult)
IOException Von der Übertragungsverbindung können keine Daten gelesen werden: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat. Int32 EndRead(System.IAsyncResult)
SocketException Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat Int32 EndReceive(System.IAsyncResult)
2019-12-17 20:45:17 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-17 20:45:17 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-17 20:45:17 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-17 20:46:30 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-17 20:46:30 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-17 20:46:30 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-17 20:47:54 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-17 20:47:54 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-17 20:47:54 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-17 20:49:05 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3/state Value:{"on":{"value":true}}:ConnectToNanoleaf | Exception: Fehler beim Senden der Anforderung. | InnerException: System.Net.Http.HttpRequestException Fehler beim Senden der Anforderung. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
WebException Die zugrunde liegende Verbindung wurde geschlossen: Unbekannter Fehler beim Empfangen.. System.Net.WebResponse EndGetResponse(System.IAsyncResult)
IOException Von der Übertragungsverbindung können keine Daten gelesen werden: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat. Int32 EndRead(System.IAsyncResult)
SocketException Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat Int32 EndReceive(System.IAsyncResult)
2019-12-17 20:49:05 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3/state Value:{"on":{"value":true}}:ConnectToNanoleaf | Exception: Fehler beim Senden der Anforderung. | InnerException: System.Net.Http.HttpRequestException Fehler beim Senden der Anforderung. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
WebException Die zugrunde liegende Verbindung wurde geschlossen: Unbekannter Fehler beim Empfangen.. System.Net.WebResponse EndGetResponse(System.IAsyncResult)
IOException Von der Übertragungsverbindung können keine Daten gelesen werden: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat. Int32 EndRead(System.IAsyncResult)
SocketException Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat Int32 EndReceive(System.IAsyncResult)
2019-12-17 20:49:05 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3/state Value:{"on":{"value":true}}:ConnectToNanoleaf | Exception: Fehler beim Senden der Anforderung. | InnerException: System.Net.Http.HttpRequestException Fehler beim Senden der Anforderung. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
WebException Die zugrunde liegende Verbindung wurde geschlossen: Unbekannter Fehler beim Empfangen.. System.Net.WebResponse EndGetResponse(System.IAsyncResult)
IOException Von der Übertragungsverbindung können keine Daten gelesen werden: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat. Int32 EndRead(System.IAsyncResult)
SocketException Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat Int32 EndReceive(System.IAsyncResult)
2019-12-18 10:11:37 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-18 10:11:37 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-18 10:14:04 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3/state Value:{"on":{"value":true}}:ConnectToNanoleaf | Exception: Fehler beim Senden der Anforderung. | InnerException: System.Net.Http.HttpRequestException Fehler beim Senden der Anforderung. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
WebException Die zugrunde liegende Verbindung wurde geschlossen: Unbekannter Fehler beim Empfangen.. System.Net.WebResponse EndGetResponse(System.IAsyncResult)
IOException Von der Übertragungsverbindung können keine Daten gelesen werden: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat. Int32 EndRead(System.IAsyncResult)
SocketException Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat Int32 EndReceive(System.IAsyncResult)
2019-12-18 10:14:04 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3/state Value:{"on":{"value":true}}:ConnectToNanoleaf | Exception: Fehler beim Senden der Anforderung. | InnerException: System.Net.Http.HttpRequestException Fehler beim Senden der Anforderung. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
WebException Die zugrunde liegende Verbindung wurde geschlossen: Unbekannter Fehler beim Empfangen.. System.Net.WebResponse EndGetResponse(System.IAsyncResult)
IOException Von der Übertragungsverbindung können keine Daten gelesen werden: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat. Int32 EndRead(System.IAsyncResult)
SocketException Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat Int32 EndReceive(System.IAsyncResult)
2019-12-18 10:14:04 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3/state Value:{"on":{"value":true}}:ConnectToNanoleaf | Exception: Fehler beim Senden der Anforderung. | InnerException: System.Net.Http.HttpRequestException Fehler beim Senden der Anforderung. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
WebException Die zugrunde liegende Verbindung wurde geschlossen: Unbekannter Fehler beim Empfangen.. System.Net.WebResponse EndGetResponse(System.IAsyncResult)
IOException Von der Übertragungsverbindung können keine Daten gelesen werden: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat. Int32 EndRead(System.IAsyncResult)
SocketException Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat Int32 EndReceive(System.IAsyncResult)
2019-12-19 11:11:45 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-19 11:11:58 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-19 11:12:11 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-19 11:27:40 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-19 11:33:50 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-19 11:34:09 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-19 11:34:22 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-19 11:34:40 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-19 11:34:40 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-19 11:34:43 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-19 11:36:22 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-19 11:36:37 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-19 11:36:50 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-19 11:36:54 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-19 11:36:54 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-19 11:37:29 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-19 11:37:29 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-19 13:31:54 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-19 13:32:07 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
2019-12-19 13:32:20 | Error | Call:http://192.168.0.110:16021/api/v1/p7rY1vD2YxRQLkLZ8SxhYtVsIhCTMsp3 Value::ConnectToNanoleaf | Exception: Eine Aufgabe wurde abgebrochen. | InnerException: System.Threading.Tasks.TaskCanceledException Eine Aufgabe wurde abgebrochen. Void ThrowForNonSuccess(System.Threading.Tasks.Task)
